### ISSUE TITLE
Create Todo List

### ISSUE THREAD

**Issue by Axe-Pearl** [Axe-Pearl/Mini-Projects#1]
###  CREATE A TO DO LIST LIKE THIS ONE - 

![Todo](https://user-images.githubusercontent.com/66417880/193990733-7de8de40-0da9-4b50-98f6-2ac3221828eb.png)
                                            
**Functionality**
- Add the Item
- Delete the Item
- Change the Order of Items(Up and Down)

**Optional-** It will be appreciated if after reloading the page order and data should be sustained.

**NOTE: To get a pull request accepted kindly follow these steps -**
Follow these steps - 
1. Star the Repository
2. Write an Article
3. Make a pull request 
4. I will merge your pull request
 
**NOTE:** Remember that you put your code in the Respective Directory - 
https://github.com/Axe-Pearl/HacktoberfestRepo/tree/master/TODO-LIST
---- -----
For more such issues and to get notified first, follow me on 
GitHub - https://github.com/Axe-Pearl
Instagram - https://www.instagram.com/anurag_nema_ytube/

Also, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff,  tips and tricks, and much more - 
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g
---- ----

**Comment by Chaitanya-087** [comment]
hi! can get more info about what article include

**Comment by Axe-Pearl** [comment]
@Chaitanya-087 Sorry for the typo, not Article this was ->
NOTE: Remember that you put your code in the Respective Directory -
https://github.com/Axe-Pearl/HacktoberfestRepo/tree/master/TODO-LIST

Thanks for Noticing

**Comment by Chaitanya-087** [comment]
ok then can you assign me this task

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by Axe-Pearl** [comment]
Sure @Chaitanya-087 , I am assigning it to you.

**Comment by RachitGarg-12** [comment]
Hey ,@Axe-Pearl  i would list to work on this task

**Comment by Axe-Pearl** [comment]
Hey @RachitGarg-12 , sure this is open to all. You can contribute to this too

**Comment by Chaitanya-087** [comment]
hi! i sent a pr

**Comment by Chaitanya-087** [comment]
@Axe-Pearl why it says not-participating in hacktoberfest profile of mine

**Comment by Axe-Pearl** [comment]
@Chaitanya-087 Can you please share the ScreenShot here, because I am already registered for Hacktoberfest.

**Comment by Axe-Pearl** [comment]
Hey @Chaitanya-087, don't worry let me check it.

**Comment by Chaitanya-087** [comment]
thank you @Axe-Pearl  its accepted now

**Comment by Axe-Pearl** [comment]
Hey, @Chaitanya-087 Thank you very much for your time and contribution, it was really a good experience working with you.

Let's Connect and learn together - 
Instagram - https://www.instagram.com/anurag_nema_ytube/

Also, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff, tips and tricks, and much more -
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g

**Comment by Chaitanya-087** [comment]
yes sure 
i followed and subscribed

**Comment by Axe-Pearl** [comment]
Thank you @Chaitanya-087

**Comment by ishaan51551** [comment]
hey plz assign to me

**Comment by ishaan51551** [comment]
plz accept my pull request

**Comment by Axe-Pearl** [comment]
Hey @ishaan51551, The same code was already contributed by another participant. 
Your contribution will be highly appreciated if you make something different. 
Best of Luck

**Comment by Axe-Pearl** [comment]
Hey @MohammadTaha0, Sure you can start working on the same.

**Comment by MohammadTaha0** [comment]
> Hey @MohammadTaha0, Sure you can start working on the same.

Okay.

**Comment by Amrutha-space** [comment]
@Axe-Pearl  Hi, I can enhance the theme and design a professional UI for the issue, let me work on this.
