### ISSUE TITLE
Newsapp using react

### ISSUE THREAD

**Issue by M-Rahul1** [Axe-Pearl/Mini-Projects#16]
Can i create a news app which gets updated daily using api. @Axe-Pearl

**Comment by anantnipunge** [comment]
hey i am Anant Nipunge . can you assign me this task ? to contribute in your project . i would love to add some features to this project. for reference i'm adding my react file in this project .

**Comment by M-Rahul1** [comment]
> Can i create a news app which gets updated daily using api. @Axe-Pearl

@Axe-Pearl ?

**Comment by anantnipunge** [comment]
Yes you can create

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anantnipunge** [comment]
But can i contribute to your project?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
