### ISSUE TITLE
You need more collaborators in order to deal with the open pull requests

### ISSUE THREAD

**Issue by rcallaby** [Axe-Pearl/Mini-Projects#32]
There is a significant number of open issues and pull requests. Adding additional collaborators may help you alleviate this workload.

**Comment by Axe-Pearl** [comment]
Hello @rcallaby, Thanks for the suggestion, and sorry for the late reply. Will plan it for sure.
Once again, thank you once again :)

**Comment by Axe-Pearl** [comment]
Hi @rcallaby, planning to add you as a collaborator.What you think about it ?

**Comment by rcallaby** [comment]
Yeah, I could help you out.
