### ISSUE TITLE
Password Generator App in vanilla JS

### ISSUE THREAD

**Issue by replyre** [Axe-Pearl/Mini-Projects#39]

**Comment by Muhammad-Rebaal** [comment]
**Password Generator**
I can create this Password Generator App in vanilla Js assign this to me..

**Comment by Kainat18** [comment]
I can create a Password Generator App in Vanilla Js , kindly assign this to me .

**Comment by dikshagupta3094** [comment]
I can create a password Generator App in vanilla Js , Kindly assign this to me

**Comment by Severus25** [comment]
Hi @Axe-Pearl, I can create a password Generator App in vanilla JS , Kindly assign this to me as I am well versed in vanilla JS.

**Comment by Muhammad-Rebaal** [comment]
@Axe-Pearl I'm the first here  and its actually my idea , then I'm very thankful if you assign this to me... :)

**Comment by xdeepraj** [comment]
Hi, is this issue still open?

**Comment by replyre** [comment]
I don't think so as a request is already merged; I shall close it now.
