### ISSUE TITLE
Create a Simple Calculator using HTML, CSS and JavaScript

### ISSUE THREAD

**Issue by Axe-Pearl** [Axe-Pearl/Mini-Projects#5]
**The issue is open for all**

**Functionality**
1. Buttons to type number
2. Buttons to add, subtract, multiply and divide
3. Button to clear everything

**Optional -** Creating more features will be appreciated and bonus point

**NOTE: To get a pull request accepted kindly follow these steps -**
Follow these steps - 
1. Star the Repository
2. Create an App
3. Make a pull request 
5. I will merge your pull request
 
**NOTE:** Remember that you put your code in the Respective Directory - 
https://github.com/Axe-Pearl/HacktoberfestRepo/tree/master/Calculator
---- -----
For more such issues and to get notified first, follow me on 
GitHub - https://github.com/Axe-Pearl
Instagram - https://www.instagram.com/anurag_nema_ytube/

Also, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff,  tips and tricks, and much more - 
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g
---- ----

**Comment by gaut2003** [comment]
Please assign this to me.

**Comment by Axe-Pearl** [comment]
Sure @gaut2003, You can start working on it.
I have assigned it to you.

**Comment by Bl5ckj5ck** [comment]
Hi @Axe-Pearl I would like to work on this

**Comment by Sengar123** [comment]
Hello @Axe-Pearl Please assign this to me.

**Comment by Akshaysrajan** [comment]
Hey @Axe-Pearl 👋🏼
Can you please assign this issue to me.
i recently created calculator project {https://akshaysrajan.github.io/NumeX/Numex.html}
i would like to contribute it to you.

**Comment by roakoth** [comment]
Hello @Axe-Pearl 
Can you please assign it to me? 
I would like to contribute.

**Comment by Akshaysrajan** [comment]
@Axe-Pearl bro your repo is excluded from Hacktoberfest please resolve it.

**Comment by Akshaysrajan** [comment]
@Axe-Pearl bro your repo is excluded from Hacktoberfest please resolve it.

**Comment by Axe-Pearl** [comment]
Hey @Akshaysrajan, I have changed the name of my Repo, may be this will work.
Can you share Screenshot of it ? I will resolve the issue soon.

**Comment by Akshaysrajan** [comment]
Screenshot attached

**Comment by DhavalDobariya333** [comment]
Please assign this to me.

**Comment by Axe-Pearl** [comment]
**Hey Everyone, Wait this repository is excluded, before I merge any pull request, I am resolving the issue.
Be Patient, and keep tuned, the problem will be fixed soon, I am closing the issue for temporary time
Thanks**
