### ISSUE TITLE
Create a Analog Clock using HTML, CSS and JS with beautiful UI

### ISSUE THREAD

**Issue by Axe-Pearl** [Axe-Pearl/Mini-Projects#7]
**The issue is open for all**

**Optional -** Creating more features will be appreciated and bonus point

**NOTE: To get a pull request accepted kindly follow these steps -**
Follow these steps - 
1. Star the Repository
2. Create an App
3. Make a pull request 
5. I will merge your pull request
 
**NOTE:** Remember that you put your code in the Respective Directory - 
https://github.com/Axe-Pearl/HacktoberfestRepo/tree/master/Clock
---- -----
For more such issues and to get notified first, follow me on 
GitHub - https://github.com/Axe-Pearl
Instagram - https://www.instagram.com/anurag_nema_ytube/

Also, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff,  tips and tricks, and much more - 
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g
---- ----

**Comment by tanmay-S12** [comment]
Hey, I would like to work on this. Do consider me assigning this issue.

**Comment by Axe-Pearl** [comment]
Hey @tanmay-S12, Sure it's open for all, you can start working.
I have assigned it to you

**Comment by Aishaa-26** [comment]
Please assign this issue to me, I am wanting to work on it.

**Comment by Axe-Pearl** [comment]
Hey Everyone, Wait this repository is excluded, before I merge any pull request, I am resolving the issue.
Thanks

**Comment by Axe-Pearl** [comment]
**Hey Everyone, Wait this repository is excluded, before I merge any pull request, I am resolving the issue.
Be Patient, and keep tuned, the problem will be fixed soon, I am closing the issue for a temporary time
Thanks**
